//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeesID { get; set; }
        public string EmployeesName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> IdentityCard { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual User User { get; set; }
    }
}
